### ISSUE TITLE
TypeError: undefined is not an object

### ISSUE THREAD

**Issue by EthanCents** [Avery246813579/Stripe-Terminal#2]
Hello!

Thanks for your work on the package!

When implementing the package, I get a few TypeErrors thrown. Specifically, when setting up the terminal:

`TypeError: undefined is not an object (evaluating 'window.location.origin')`

and then when trying to discover readers:

`TypeError: undefined is not an object (evaluating '_this3.terminalInstance.discoverReaders')`

It should be noted that I'm actually able to generate the connection token, it's just that this TypeError is thrown.

On the other hand, the discoverReader method is a different issue. For simplicity, I have a TouchableOpacity, where onPress calls this method:

```
  discoverReaders = async () => {
    console.log('discoverReaders called');
    
    const discoverResult = await StripeTerminal.discoverReaders({simulated: false});

    if (discoverResult.error) {
      console.log("Failed to discover: ", discoverResult.error);
      return discoverResult.error;
    } else {
      this.setState({
        discoveredReaders: discoverResult.discoveredReaders
      });
      console.log(discoverResult.discoveredReaders);
      return discoverResult.discoveredReaders;
    }
  };
```

Any idea why this may be happening? And any suggestions on a better flow for this outside of a button click that may lead to a solution?

**Comment by Avery246813579** [comment]
@EthanCents,

I just pushed a new version 2.0.2, could you please try it out. It should fix both errors that are happening. 

The flow I use is when my app starts up and the user is signed in, I use `StripeJavascriptTerminal.setup` to set up my client with Stripe. Then I check if they have any readers connected to their location using the code below. 

```javascript
let {discoveredReaders} = await StripeJavascriptTerminal.discoverReaders({
    simulated: false,
    location: location.STRIPE_LOCATION_ID
});
```

If there are no discovered readers I wait until they set up a reader to continue with connecting, but if they do have a reader I will finish their setup using `StripeJavascriptTerminal.connectReader`. 

If the new version didn't fix the issue or if you have any more questions please do reach out.

**Comment by EthanCents** [comment]
That's awesome @Avery246813579 ! Thanks for the quick response. It looks like the undefined is not an object error is no longer an issue. I did get a warning that I believe has to do with [this line](https://github.com/Avery246813579/Stripe-Terminal/blob/29fc0bdee6bf223d3c75cd74dedabc057e39e65d/src/index.js#L42):

`SyntaxError: Unexpected identifier 'Native'. Expected '}' to end an object literal.`

Idk, could be my code as well.

Separately - if you're not using a button or some sort of visual cue, where are you calling `discoverReaders()`? In `componentDidMount()`, or somewhere else? I guess I'm trying to figure out the best flow and order of operations (ideally I'd like to not show a button but can't seem to get that off the ground)

**Comment by EthanCents** [comment]
I can verify that if I have things set up to discover readers via a button, I still get this:

```
TypeError: undefined is not an object (evaluating '_this3.terminalInstance.discoverReaders')
```

You could bucket this as an improvement as well, but maybe an example app showing your implementation would be helpful for documentation purposes. I'd also be happy to help contribute to the package/project!

**Comment by Avery246813579** [comment]
@EthanCents,

The first error prevents the terminal instance from being discovered. I changed something to a string and forgot quotes. It should be good now with build 2.0.3.

I call those methods inside a componentDidMount. You have to make sure you already register the reader before calling `discoverReaders` or you will get no readers back. I can add an example into the README.

**Comment by EthanCents** [comment]
@Avery246813579 nice! That seems to have cleared things up for me. I was also able to discover readers, albeit still fine-tuning it.

Just curious, you ever run into this: `ReferenceError: Can't find variable: btoa`?

**Comment by EthanCents** [comment]
Nevermind, fixed the issue. In case anyone else runs into this issue, perform the following:

`yarn add base-64`;

Navigate to `index.js` and add:

```
import { decode, encode } from 'base-64';

...

if (!global.btoa) {
  global.btoa = encode;
}

if (!global.atob) {
  global.atob = decode;
}
```

**Comment by Avery246813579** [comment]
@EthanCents what method is being used when that error shows up? I can add that if it's not already being added.

**Comment by EthanCents** [comment]
@Avery246813579 it affected me in particular when running `connectReader()`. I know `btoa` is being utilized in the underlying JS SDK, but it could also be related to other dependencies I have in my code. 

Either way, might not hurt to add. I should note though that I added that snippet above to my own `index.js` for my React Native project, not your underlying code.

**Comment by EthanCents** [comment]
Hey @Avery246813579 ,

Wanted to bring some other issues/interesting use cases to your attention. 

Let's say I have a component, and in my componentDidMount(), I'm running the following:

```
  async componentDidMount() {

    await StripeTerminal.setup({
      onFetchConnectionToken: async () => {
        let connectionTokenResult = this.fetchConnectionToken();
        return connectionTokenResult;
      },
      onUnexpectedReaderDisconnect: () => {
        alert("Card reader has disconnected");
      }
    });
  }
```

then I have this as my `fetchConnectionToken()`:

```
  fetchConnectionToken = async () => {
    const baseUrl = Config.BASE_URL;
    
    return fetch(`${baseUrl}stripe/connectionToken/create`, { method: "POST" })
      .then(function(response) {
        return response.json();
      })
      .then(function(data) {
        console.log('stripe connection token: ' + data.secret.secret);
        return data.secret.secret;
      })
      .catch(function(error) {
        return error.message;
      });
  }
```

There are some inconsistent patterns that occur here. Sometimes, the connection token is actually initialized. Other times, `fetchConnectionToken()` doesn't even get recognized or called.

Oddly enough, if I change things up a bit so my setup within componentDidMount() looks like:

```
    await StripeTerminal.setup({
      onFetchConnectionToken: this.fetchConnectionToken();
      onUnexpectedReaderDisconnect: () => {
        alert("Card reader has disconnected");
      }
    });
```

The actual token is generated and displayed, but very shortly after this error gets generated:

```
Error: Invalid argument: Invalid `onFetchConnectionToken` handler given.
            You must pass a function that will retreive an connection token via your backend using your api secret key.
```

have you seen this behavior before?
